### ISSUE TITLE
[BE] 폐수거함 조회시 후보 여부 포함

### ISSUE THREAD

**Issue by wltks98** [Yukhoebibimbap/huemap#114]

**Comment by wltks98** [comment]
isCandidate를 responseDto에 넣으려는 과정에서 isCandidate를 mapStruct가 맵핑하지 못하는 문제가 발생했습니다
알아보니 mapStruct는 is뒤에 대문자가 붙은 변수를 맵핑하지 못한다고 합니다
이에 해결방안은 
1. iscandidate로 고친다
2. has~로 고친다
3. 직접 메소드를 만든다
어떤 것이 좋겠습니까? @ecvheo1

**Comment by ecvheo1** [comment]
3번으로 해서 유동적으로 대응하는 것이 좋을 것 같습니다!
