### ISSUE TITLE
[BE] soft delete vs hard delete

### ISSUE THREAD

**Issue by ecvheo1** [Yukhoebibimbap/huemap#70]
잘못된 폐수거함 위치 제보 기능을 구현하려던 중에 데이터 삭제 관련해서 이야기 나눠야할 것이 있어 이슈를 작성하게 되었습니다.

데이터를 삭제 처리하는 방법에는 여러가지 방법이 있습니다.
1. 실제 삭제한다. (hard delete)
2. delete 필드를 두어 T/F로 두는 방법(soft delete)
3. 삭제할 데이터는 삭제 테이블로 이동시키는 것

현재 잘못된 폐수거함 위치 제보, 즉 허위 폐수거함 제보 엔티티가 있는데, 사용자로부터 해당 폐수거함에 대한 허위 제보를 3개 이상 받으면 폐수거함을 삭제해야하는 정책을 가져가기로 하였습니다.
이에 대해서 제가 생각하였을 때는 soft delete를 두어서 실제 데이터를 삭제하지 않는 방향이 더 나은 거 같습니다. 그 이유는 다음과 같습니다.
휴맵의 데이터들은 모두 각 기관에서 제공해주는 공공데이터에 의존하고 있고, 폐수거함에 대한 데이터들을 사용자 간의 상호작용으로 업데이트될 수 있습니다. 또한 폐수거함 관리 기관이 해당 데이터를 요청할 수도 있습니다. 만약 hard delete로 삭제하게 된다면, 공공데이터에 현재 올라와있는 폐수거함 데이터와 동기화가 되어 있지 않고, 과거 폐수거함 데이터를 따로 조회하는 요구사항에 대응하지 못할 것 같습니다.

하지만 soft delete를 적용하게 된다면 query 할 때 WHERE 절을 추가로 걸어야하기 때문에 실수가 발생할 가능성이 있습니다.

이에 대해서 어떻게 생각하시는지 이야기 나눠보고 결정하는 것이 좋을거 같습니다. @wltks98

**Comment by wltks98** [comment]
제 생각에도 2번의 soft delete가 가장 나아 보입니다 
관련 자료를 찾아봤는데 https://www.baeldung.com/spring-jpa-soft-delete 여기서 처럼
@SQLDelete(sql = "UPDATE table_product SET deleted = true WHERE id=?")
@Where(clause = "deleted=false")
이렇게 엔티티에 선언하면 폐수거함 삭제시 자동으로 deleted가 true가 되며 @Where을 통해 where절을 추가 하지 않아도 기본으로 deleted가 false인 데이터만 조회한다고 합니다 @ecvheo1

**Comment by ecvheo1** [comment]
오 관련 문서가 있군요. 👍 
soft delete로 적용하도록 하겠습니다..
